Fix solver name conflict
transition-zero/tz-osemosys pull request #153
Opened 2024-11-13 14:00 UTC by ollie-bell

### Description
Please explain the changes you made here.

### Checklist
- [ ] Dependencies install correctly in a clean environment and code executes;
- [ ] Test coverage extended; created tests fail without the change (if possible);
- [ ] All tests passing;
- [ ] Commits follow a type convention (e.g. https://gist.github.com/brianclements/841ea7bffdb01346392c#type);
- [ ] Extended the README, documentation and/or docstrings, if necessary;

2024-11-13 14:08 UTC, ollie-bell commented on tz/osemosys/model/model.py
> -
this is handled by linopy anyway

2024-11-13 14:09 UTC, ollie-bell commented on tz/osemosys/model/model.py
> +        self._m.solve(**linopy_solve_kwargs)
Now the `solver` kwarg ([which is a HiGHS option](https://ergo-code.github.io/HiGHS/dev/options/definitions/#option-solver)) can be used alongside `solver_name`

2024-11-14 11:13 UTC, edwardxtg approved these changes
lgtm.

Do we need to extend test coverage at all? Given all the tests in test_solve.py have been updated to use "solver_name="

Let's figure out a way of communicating breaking releases before either merging this or releasing a new osemosys version.

2024-11-14 12:21 UTC, ollie-bell commented
A more staged approach might be something like this:

```python
def solve(self, solver: str | None = None, solver_options: dict = {}, **linopy_solve_kwargs: Any):
    if solver is not None:
        warnings.warn("'solver' argument will be deprecated in a future release, please use 'solver_name' instead")
        if "solver_name" in linopy_solve_kwargs:
            raise ValueError(f"received input for deprecated "solver" and "solver_name", please use "solver_name" instead")
        linopy_solve_kwargs.update({"solver_name": solver})
    
    self._m.solve(**linopy_solve_kwargs, **solver_options)
```

Now Aman's problem goes away using `model.solve(solver='highs', solver_options={'solver': 'pdlb'})` (but this will print a deprecation warning until updating to use `solver_name` instead of `solver`).

Note actually that we could just use this function signature without needing to do any deprecation, but I feel like it's cleaner to use the same argument naming that linopy uses.

2024-11-14 16:10 UTC, edwardxtg commented
@ollie-bell agree is best to adopt the same naming as linopy. 

And i like your suggestion for the DeprecationWarning, but when would we then implement the actual change? x months down the line?

2025-02-17 09:49 UTC, ollie-bell commented
@edwardxtg can you have another look at this please? I've added another couple of changes and think we should just merge without any deprecation warning. We can make the release 0.1.0 to mark that there has been a "breaking" change.

2025-02-17 11:21 UTC, ollie-bell commented on pyproject.toml
> +find = { include = ["tz.*"] }
stops things like `examples` being included in the distribution

2025-02-17 12:10 UTC, edwardxtg requested changes
Would be good if you can add a few small comments explaining the most recent changes you've made.

2025-02-17 12:12 UTC, ollie-bell commented on tz/osemosys/model/model.py
> -            self._m.to_file(lp_path)
removing this because it feels unnecessary.. a user can call `model._m.to_file(path)` if they want, but no need for it to live here AFAICT

2025-02-17 12:13 UTC, ollie-bell commented on tz/osemosys/model/model.py
> +        return self._m.status, self._m.termination_condition
returning both status and termination condition as both have different semantics, and this is consistent with the return value from pypsa optimise.

2025-02-17 12:15 UTC, ollie-bell commented on tz/osemosys/model/model.py
> +        if force or not hasattr(self, "_data") or not hasattr(self, "_m"):
can now call `model._build()` independently of `model.solve()` without it needing to rebuild. Consistent with pypsa `network.optimize.create_model()`...

2025-02-17 12:25 UTC, edwardxtg approved these changes

2025-02-17 12:27 UTC, merged