New feature region grouping v2
transition-zero/tz-osemosys pull request #156
Opened 2024-12-05 16:04 UTC by djwels

### Description
Added new set for user defined region groups.

User can assign nodes to a region group and set national level targets (e.g. emissions reduction, RE targets etc.)

Tested at the moment for emissions reduction

Tested on a larger 3 node PHL model and solved within a reasonable time.

### Checklist
- [ ] Dependencies install correctly in a clean environment and code executes;
- [ ] Test coverage extended; created tests fail without the change (if possible);
- [ ] All tests passing;
- [ ] Commits follow a type convention (e.g. https://gist.github.com/brianclements/841ea7bffdb01346392c#type);
- [ ] Extended the README, documentation and/or docstrings, if necessary;

2025-03-21 14:21 UTC, edwardxtg requested changes
Great work on this overall, I've left a couple comments to do with the tests.

When I tried to run all the pytests i got quite a few failing tests.

Please could you check if you get the same errors and try deal with them? I unfortunately dont have much time to do much work on this myself.

![image](https://github.com/user-attachments/assets/a7db114b-36f0-4fc4-88bd-613904403f6c)

2025-03-21 14:21 UTC, edwardxtg commented on tests/test_solve/test_solve.py
> +EXAMPLE_YAML = "/home/dwelsby/repos/tz-osemosys/examples/phl_s5_Accelerated_Transition/"
Could you revert this and add a new test to test the region groups?

2025-03-21 14:21 UTC, edwardxtg commented on tests/test_solve/test_solve.py
> +# def test_model_solve_from_otoole_csv():
uncomment tests please

2025-03-21 16:31 UTC, abhishek0208 reviewed
@djwels Looks good to me too, but could you please add the PHL example to test with?
Nice work!

2025-03-21 16:31 UTC, abhishek0208 commented on tests/test_solve/test_to_xr_ds.py
> +EXAMPLE_YAML = "/home/dwelsby/repos/tz-osemosys/examples/utopia"
Hard-coded to local example?

2025-03-21 17:33 UTC, abhishek0208 commented
Thanks for sending over the example PHL model. Region grouping works well, great work!

2025-03-31 13:18 UTC, djwels commented
@edwardxtg I have pushed some changes and think this has resolved the errors we were getting. Would you be able to check from your side?

2025-05-12 20:10 UTC, djwels commented
@edwardxtg ive added a region group test in a seperate pytest file: https://github.com/transition-zero/tz-osemosys/blob/new_feature_region_grouping_v2/tests/test_solve/test_region_group.py

2025-05-19 15:01 UTC, edwardxtg approved these changes

2025-05-19 15:14 UTC, merged